#!awk
# list non duplicate lines
# Idea of Byron Rakitzis
# Arnold Robbins, arnold@gnu.ai.mit.edu

{
  for (i = 1; i< NF; i++)
      freq[$i]++
}

END {
      n = sort(freq)
      for (word in freq)
          printf "%s\t%d\n", word, freq[word]
    }
